language: cpp
compiler:
- gcc
branches:
  only:
  - master
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- pwd
- git submodule update --init --recursive
- echo yes | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
- echo yes | sudo apt-add-repository ppa:boost-latest/ppa
- echo yes | sudo apt-add-repository ppa:kalakris/cmake
- echo yes | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq libboost1.54-all-dev libsdl2-dev libsdl2-image-dev libsdl-ttf2.0-dev zlib1g-dev
  libbz2-dev doxygen libfreetype6-dev libpython2.7 libsdl2-mixer-dev cmake qtdeclarative5-dev libpng12-dev zlib1g-dev libenet-dev graphviz
- wget http://wheybags.netsoc.ie/pkg/librocket_1.3-1_amd64.deb
- sudo dpkg -i librocket_1.3-1_amd64.deb
- wget http://wheybags.netsoc.ie/pkg/librocket-dev_1.3-1_amd64.deb
- sudo dpkg -i librocket-dev_1.3-1_amd64.deb

before_script:
- mkdir build
- cd build
- cmake ../ -DCMAKE_CXX_FLAGS="-Werror"
script:
- make
after_success: 
- cd ..
- ./update-gh-pages.sh
notifications:
  recipients:
  - wheybags+travis.ci@wheybags.com
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: b9143BbjFmQvaxruDHiUy1sW4InyZGejs4S/xgb4W1fFTzea9EMpzjWgwospBI3NPpe6xadctdypL9UbzJMXfD0PAZ39FbMIgl56pFkoZv1G9vwLOjG6ka0wXT7Pr6yP2FHkIdrQWECvvc1shTFXU9Yeystl0ISPwgphWUlwFZU=
